### PR TITLE
Feat bandedeigen

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
This pull request hoists the band reduction algorithms from LAPACK out of Fortran and into Julia. Why? This permits storage of the eigenvectors of a symmetric banded matrix as a new abstract matrix that contains the list of Givens rotations for band reduction and the dense eigenvectors of the similar symmetric tridiagonal matrices.

LAPACK isn't object-oriented, so their banded eigensolvers were conceived to return dense matrices. However, if one accepts eigenvectors in structured form, the *algorithms* for banded eigensolvers only cost O(n<sup>2</sup>), and the `BandedEigenvectors` retain an O(n<sup>2</sup>) matrix-vector product.

The savings can be significant:
```julia
julia> using BandedMatrices

julia> j = 1;

julia> N = round.(Int, 100 * exp2.(range(0,stop = 6, length = 15)))
15-element Array{Int64,1}:
  100
  135
  181
  244
  328
  442
  594
  800
 1077
 1449
 1950
 2625
 3533
 4755
 6400

julia> t = zeros(length(N), 3);

julia> for n in N
           b = 4
           A = BandedMatrix{Float64}(undef, n, n, 0, b);
           A[band(0)] .= (1:n).^2
           for k in 1:b
               A[band(k)] .= 2/(k+1);
           end
           A = Symmetric(A);
           t[j, 1] = @elapsed F = bandedeigen(A);
           t[j, 2] = @elapsed eigen(A);
           t[j, 3] = @elapsed eigen(Symmetric(Matrix(A)));
           global j += 1
       end

julia> t
15×3 Array{Float64,2}:
 0.000902796    0.00229626   0.00219533
 0.00186702     0.0053129    0.00453066
 0.00321211     0.0110738    0.00622061
 0.0053263      0.0250456    0.0107388 
 0.00878451     0.0489528    0.017925  
 0.0307746      0.124361     0.0416343 
 0.029362       0.5965       0.091619  
 0.0488776      1.69239      0.185796  
 0.0867473      4.06763      0.39925   
 0.22365        8.89001      0.817204  
 0.298682      18.7646       1.61202   
 0.618353      40.5231       3.17417   
 1.23958       87.1322       6.19219   
 2.36332      196.425       12.6528    
 4.94099      457.331       29.0651    

julia> [fill(1, length(N)) log2.(N)]\log2.(t)
2×3 Array{Float64,2}:
 -23.4687  -28.9918   -24.6186 
   2.0147    3.02111    2.31174
```

### CODE REVIEW

**Comment by dlfivefifty** [comment]
This doesn't seem like the "right" way to design this: I would start from the Base code for `Eigen`, that is, we could have `BandedEigen <: Factorization`. Then if `F isa BandedEigen`, `F.V` returns a `BandedEigenvectors`. 

There shouldn't be a `bandedeigen` function at all, `eigen(::Symmetric{T,BandedMatrix{T}})` should return a `BandedEigen`.

**Comment by MikaelSlevinsky** [comment]
That's an easy fix and I contemplated that. But I wasn't sure how strongly anyone would object to the default `eigen` not returning something dense.

`BandedEigen{T}` is really a typealias for `Eigen{T, T, Vector{T}, BandedEigenvectors{T}}`. So perhaps a call to `Eigen{Float64, Float64, Vector{Float64}, Matrix{Float64}}(B::BandedEigen{Float64})` is how to convert representations.

**Comment by dlfivefifty** [comment]
Everywhere in Julia prefers preserving sparsity, and the same argument would apply to ` qr `,  so overloading ` eigen ` is definitely the way to go.

I can’t think of any reason people would want dense eigenvectors.. and if they do they can call ` Matrix(F.vectors) `.

I like the idea of using ` Eigen ` with a specialised vector type

**Comment by MikaelSlevinsky** [comment]
Something interesting about this is that because almost all of the arithmetic is still delegated to LAPACK through `ccall`s to more elementary LAPACK functions, the machine code that Julia generates should be almost identical to the LAPACK function `sbtrd.f` if it were compiled with LLVM.

I also added a function `compress!` that applies the Givens rotations into the eigenvectors of the similar tridiagonal matrices and `pop!`s them from storage. This can give the user the ability to recover the (faster) dense eigenmatrix-vector multiplication if they want to, akin to "deferring" the O(n<sup>3</sup>) computation.

**Comment by MikaelSlevinsky** [comment]
Ok, this is ready for consideration. I've also included methods to extract the fast generalized eigendecomposition for symmetric-definite and banded pencils. (Fortunately, the Givens rotations that are used to chase bulges off the bands commute with just the right portions of the split-Cholesky factors; these factors need not be deconstructed!)

**Comment by dlfivefifty** [comment]
Can you pull master to fix the break test?

**Comment by MikaelSlevinsky** [comment]
The tests pass after pulling in master.

**Comment by devonwp** [comment]
I am confused why the old `sbev` was so much slower for the case of computing just eigenvalues. If I understand the [LAPACK documentation](https://www.netlib.org/lapack/lug/node48.html) correctly, `sbev` in the case of computing all eigenvalues should tridiagonalize and call `sterf` on the symmetric tridiagonal matrix which computes all eigenvalues and no eigenvectors. So given that no eigenvectors are being computed, it is unclear to me why it should matter how eigenvectors are stored in the general case of a banded eigenpair problem. It looks like I misunderstand something though... @MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
Hi @devonwp, I think for eigenvalues only you should be fine. This PR is about eigenvectors in structured form.

**Pull request merged**
