### PR TITLE
Ac_mul_B, A_mul_Bc and Ac_mul_Bc

### PR DESCRIPTION
**Pull request by randy3k**
Now only works with matrices with bandwidth < 100 (for these matrices, the pure Julian code is used).

### CODE REVIEW

**Comment by dlfivefifty** [comment]
What's the status of this? I'd like to tag a new release of BandedMatrices (so I can tag depending packages)

**Comment by randy3k** [comment]
We now only have pure Julia methods for A' * B, A * B' and A' * B'. Theoretically, it should be faster to use lapack routines if bandwidths is large (simulations suggested that lapack routines are better for bandwidth >100).

Other than that, it is working. I guess we can merge it now and improve it later.

**Comment by dlfivefifty** [comment]
OK, let's do that.

**Comment by dlfivefifty** [comment]
This is bizarre, these changes have thrown some compile times through the roof:
```julia
julia> x = Fun()
Fun(Chebyshev(【-1.0,1.0】),[0.0, 1.0])

julia> @time cos(x) # used to be 20s
208.276366 seconds (741.09 M allocations: 36.486 GiB, 9.12% gc time)
```

**Comment by randy3k** [comment]
Ya, but ScoopCompile is broken for Julia 0.6 though

**Comment by dlfivefifty** [comment]
We can just continue to use the same precompile.jl file though

**Comment by dlfivefifty** [comment]
Fixing a dynamic typing issue in ApproxFun has reduced this to
```julia
julia> @time cos(x)
 11.288219 seconds (12.62 M allocations: 600.293 MiB, 3.02% gc time)
```

**Comment by randy3k** [comment]
Great!

**Pull request merged**
